export enum REL {
  HUSBAND = 'Husband',
  WIFE = 'Wife',
  SON = 'Son',
  DAUGHTER = 'Daughter',
  RELATIVE = 'Relative',
  SISTER = 'Sister',
  BROTHER = 'Brother',
  NIECE = 'Niece',
  NEPHEW = 'Nephew',
  CONTACT = 'Contact',
  HOUSEHOLD = 'Household',
  HOUSEHOLD_MEMBER = 'Household member',
  EXPOSURE = 'With Exposure',
  EXPOSURE_HISTORY = 'With Exposure History',
}
